version: '3'
services:

  back-end:
    build: .
    image: "students.jar"
    container_name: students.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  front-end:
    build: frontend/students/
    image: "students-ui"
    container_name: students-ui
    ports:
      - "3000:3000"
    links:
      - back-end
